[features]
seeds = false
[programs.devnet]
gifportal = "EdwdsKiu6Y7XWQUKAHmwh63nqvyAFipKnDQzgaV3iCaj"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/qasimrehman/.config/solana/id.json"

[scripts]
test = "node tests/gifportal.js"
